# Generated by Django 4.0.4 on 2022-08-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipolls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chouce',
            new_name='Choice',
        ),
    ]
